### ISSUE TITLE
rtmp流无法投屏 

### ISSUE THREAD

**Issue by hhszzheng** [lebosdk/LBLelinkKit#1]
rtmp流无法投屏，显示DLNA失败。其他格式可以正常投屏。

**Comment by lebosdk** [comment]
rtmp是支持的，我们支持的格式有，"rtmp,async,cache,crypto,file,http,https,ijkhttphook,ijkinject,ijklivehook,ijklongurl,ijksegment,ijktcphook,pipe,rtp,tcp,tls,udp,ijkurlhook,data"...

你可以使用最新的版本试试，但是接收端TV也需要更新成我们最新的版本，有问题再联系！感谢你的关注
