### ISSUE TITLE
制作的私有库内依赖LBLelinkKit后，验证不通过

### ISSUE THREAD

**Issue by kaioser** [lebosdk/LBLelinkKit#10]
podspec文件如下：
<img width="440" alt="截屏2021-03-04 下午6 51 19" src="https://user-images.githubusercontent.com/30762999/109953200-b426de80-7d1a-11eb-9afb-41515fd80eb9.png">

报错信息如下：
![截屏2021-03-04 下午6 51 42](https://user-images.githubusercontent.com/30762999/109953239-c30d9100-7d1a-11eb-990e-83217dc9a359.png)

**Comment by lebosdk** [comment]
已经更新版本，修改了platform的版本号，请用新版本试试看

**Comment by lebosdk** [comment]
github和cocoapods都已经更新到31306版本了，可尝试用这个最新版本试试看
