### ISSUE TITLE
缺少本地网络访问所需的配置，Info.plist中需要配置,兼容iOS14

### ISSUE THREAD

**Issue by HZTonyAng** [lebosdk/LBLelinkKit#11]
Binary file ./Pods/LBLelinkKit/LBLelinkKit.framework/LBLelinkKit matches
./Pods/LBLelinkKit/LBLelinkKit.framework/Headers/LBLelinkError.h:   
 LBLelinkBrowserErrorMissingRequiredConfiguration = -1500,       // 缺少本地网络访问所需的配置，Info.plist中需要配置NSBonjourServices(_leboremote._tcp)和NSLocalNetworkUsageDescription，兼容iOS14

**Comment by lebosdk** [comment]
Info.plist中需要配置NSBonjourServices(_leboremote._tcp)和NSLocalNetworkUsageDescription，兼容iOS14

**Comment by lebosdk** [comment]
详细集成过程可参照：https://doc.hpplay.com.cn/web/#/1/55
