### ISSUE TITLE
SDK Connect Crash

### ISSUE THREAD

**Issue by peter-Kings** [lebosdk/LBLelinkKit#13]
是否越狱:否

机型版本：iPhone10,3

使用时长（s）：2056.58

前后台状态：前台

网络类型：wifi

系统：ios

系统版本：15.2

错误发生时间：2022-01-08 18:22:07

服务端接收时间：2022-01-08 18:26:26

SDK版本号：1.5.5

pod 'LBLelinkKit', '30706'

Code:

private var lelinkConnection: LBLelinkConnection?
private var lelinkPlayer: LBLelinkPlayer?
private var playingUrl: URL?
//连接
func play(_ url: URL, recordType: PlayingRecordType, in device: LBLelinkService) {
        lelinkBrowser.stop()
        
        playingUrl = url
        currentDevice = device

        if let oldConnect = self.lelinkConnection {
            oldConnect.delegate = nil
            oldConnect.disConnect()
        }
        self.lelinkConnection = LBLelinkConnection()
        self.lelinkConnection?.delegate = self
        self.lelinkConnection?.lelinkService = device
        
        self.lelinkConnection?.connect()
        
        postProgress(recordType: recordType)
}
//播放
func lelinkConnection(_ connection: LBLelinkConnection, didConnectTo service: LBLelinkService) {
        
        lelinkPlayer = LBLelinkPlayer()
        lelinkPlayer?.delegate = self
        lelinkPlayer?.lelinkConnection = connection
        
        let playItem = LBLelinkPlayerItem()
        playItem.mediaType = .videoOnline
        playItem.mediaURLString = playingUrl?.absoluteString ?? ""
        
        lelinkPlayer?.play(with: playItem)
}

以下为崩溃堆栈：

CrashDoctor Diagnosis: Attempted to dereference garbage pointer 0x20.
Originated at or in a subcall of std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char)
Thread 0:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   GraphicsServices                    0x00000001a11c59a0 GSEventRunModal
6   UIKitCore                           0x000000018366a600 -[UIApplication _run]
7   UIKitCore                           0x00000001833ffb08 UIApplicationMain
8   mama                                0x0000000104d73f20 main + [AppDelegate.swift : 30] 
9   (null) 0x0000000108334250 0x0 + 4432544336
Thread 1 name:  com.apple.uikit.eventfetch-thread
Thread 1:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   Foundation                          0x00000001825703cc -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   Foundation                          0x00000001825aec3c -[NSRunLoop(NSRunLoop) runUntilDate:]
7   UIKitCore                           0x00000001835e8348 -[UIEventFetcher threadMain]
8   Foundation                          0x00000001825bc8ac __NSThread__start__
9   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 2 name:  Realm notification listener
Thread 2:
0   libsystem_kernel.dylib              0x00000001baf262f8 kevent
1   mama                                0x0000000106530b98 realm::_impl::ExternalCommitHelper::listen()
2   mama                                0x0000000106530ce0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*)
3   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 3 name:  JavaScriptCore bmalloc scavenger
Thread 3:
0   libsystem_kernel.dylib              0x00000001baf254f0 __psynch_cvwait
1   libsystem_pthread.dylib             0x00000001db3b78b8 _pthread_cond_wait$VARIANT$armv81
2   libc++.1.dylib                      0x00000001982a22b8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)
3   JavaScriptCore                      0x000000018c491c4c void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&)
4   JavaScriptCore                      0x000000018c496708 bmalloc::Scavenger::threadRunLoop()
5   JavaScriptCore                      0x000000018c4960bc bmalloc::Scavenger::Scavenger(std::__1::scoped_lock<bmalloc::Mutex> const&)
6   JavaScriptCore                      0x000000018c49775c std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*)
7   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 4 name:  Realm notification listener
Thread 4:
0   libsystem_kernel.dylib              0x00000001baf262f8 kevent
1   mama                                0x0000000106530b98 realm::_impl::ExternalCommitHelper::listen()
2   mama                                0x0000000106530ce0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*)
3   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 5 name:  com.apple.NSURLConnectionLoader
Thread 5:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   CFNetwork                           0x000000018183bc88 _CFURLStorageSessionCopyIdentifier
6   Foundation                          0x00000001825bc8ac __NSThread__start__
7   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 6 name:  AVAudioSession Notify Thread
Thread 6:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   AudioSession                        0x0000000189a31d7c CADeprecated::GenericRunLoopThread::Entry(void*)
6   AudioSession                        0x0000000189a3b0ac CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*)
7   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 7:
0   libsystem_kernel.dylib              0x00000001baf25088 __semwait_signal
1   libsystem_c.dylib                   0x000000018b3878e0 nanosleep
2   libsystem_c.dylib                   0x000000018b39b28c sleep
3   mama                                0x0000000106cb30c4 monitorCachedData + [KSCrashCachedData.c : 0] 
4   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 8 name:  KSCrash Exception Handler (Secondary)
Thread 8:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   mama                                0x0000000106c82900 handleExceptions + [KSCrashMonitor_MachException.c : 0] 
3   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 9 name:  KSCrash Exception Handler (Primary)
Thread 9:
0   (null) 0x0000000000000000 0x0 + 0
Thread 10 name:  com.apple.CoreMotion.MotionThread
Thread 10:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   CoreFoundation                      0x0000000180eb1300 CFRunLoopRun
6   CoreMotion                          0x000000018d2cd184 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type)
7   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 11 name:  com.apple.CFNetwork.CustomProtocols
Thread 11:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   CFNetwork                           0x000000018183bc88 _CFURLStorageSessionCopyIdentifier
6   Foundation                          0x00000001825bc8ac __NSThread__start__
7   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 12 name:  com.apple.CFStream.LegacyThread
Thread 12:
0   libsystem_kernel.dylib              0x00000001baf24b10 mach_msg_trap
1   libsystem_kernel.dylib              0x00000001baf25134 mach_msg
2   CoreFoundation                      0x0000000180e1fb60 __CFRunLoopServiceMachPort
3   CoreFoundation                      0x0000000180e23c48 __CFRunLoopRun
4   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
5   CoreFoundation                      0x0000000180f13bb4 _legacyStreamRunLoop_workThread
6   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 13 name:  com.apple.CFSocket.private
Thread 13:
0   libsystem_kernel.dylib              0x00000001baf2571c __select
1   CoreFoundation                      0x0000000180ebb79c __CFSocketManager
2   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 14:
0   libsystem_kernel.dylib              0x00000001baf24b64 semaphore_timedwait_trap
1   libdispatch.dylib                   0x0000000180b4672c _dispatch_sema4_timedwait$VARIANT$armv81
2   libdispatch.dylib                   0x0000000180b46cbc _dispatch_semaphore_wait_slow
3   mama                                0x00000001066fea48 __31-[LBLelinkService checkLelink:]_block_invoke
4   libdispatch.dylib                   0x0000000180b761a4 _dispatch_call_block_and_release
5   libdispatch.dylib                   0x0000000180b771a8 _dispatch_client_callout
6   libdispatch.dylib                   0x0000000180b4e724 _dispatch_continuation_pop$VARIANT$armv81
7   libdispatch.dylib                   0x0000000180b4dee8 _dispatch_async_redirect_invoke
8   libdispatch.dylib                   0x0000000180b5b2f0 _dispatch_root_queue_drain
9   libdispatch.dylib                   0x0000000180b5bacc _dispatch_worker_thread2
10  libsystem_pthread.dylib             0x00000001db3b6e48 _pthread_wqthread
Thread 15:
0   libsystem_pthread.dylib             0x00000001db3b69e8 start_wqthread
Thread 16:
0   libsystem_kernel.dylib              0x00000001baf29e30 __connect
1   mama                                0x0000000106757384 __51-[LEBAsyncSocket connectSocket:address:stateIndex:]_block_invoke
2   libdispatch.dylib                   0x0000000180b761a4 _dispatch_call_block_and_release
3   libdispatch.dylib                   0x0000000180b771a8 _dispatch_client_callout
4   libdispatch.dylib                   0x0000000180b4e3cc _dispatch_queue_override_invoke
5   libdispatch.dylib                   0x0000000180b5b2f0 _dispatch_root_queue_drain
6   libdispatch.dylib                   0x0000000180b5bacc _dispatch_worker_thread2
7   libsystem_pthread.dylib             0x00000001db3b6e48 _pthread_wqthread
Thread 17:
0   libsystem_pthread.dylib             0x00000001db3b69e8 start_wqthread
Thread 18:
0   libsystem_pthread.dylib             0x00000001db3b69e8 start_wqthread
Thread 19:
0   libsystem_kernel.dylib              0x00000001baf250cc __workq_kernreturn
1   libsystem_pthread.dylib             0x00000001db3b6ed0 _pthread_wqthread
Thread 20:
0   libsystem_kernel.dylib              0x00000001baf250cc __workq_kernreturn
1   libsystem_pthread.dylib             0x00000001db3b6ed0 _pthread_wqthread
Thread 21:
0   libsystem_pthread.dylib             0x00000001db3b69e8 start_wqthread
Thread 22:
0   libnetwork.dylib                    0x0000000181f44efc nw_socket_add_input_handler
1   libnetwork.dylib                    0x0000000181c1fd90 nw_endpoint_flow_attach_socket_protocol
2   libnetwork.dylib                    0x0000000181c13240 nw_endpoint_flow_attach_protocols
3   libnetwork.dylib                    0x0000000181aa1af4 nw_endpoint_flow_setup_protocols
4   libnetwork.dylib                    0x0000000181a9de28 -[NWConcrete_nw_endpoint_flow startWithHandler:]
5   libnetwork.dylib                    0x0000000181afe158 nw_endpoint_handler_path_change
6   libnetwork.dylib                    0x0000000181b27d3c nw_endpoint_handler_start
7   libnetwork.dylib                    0x0000000181b2d66c __nw_connection_start_block_invoke
8   libdispatch.dylib                   0x0000000180b761a4 _dispatch_call_block_and_release
9   libdispatch.dylib                   0x0000000180b771a8 _dispatch_client_callout
10  libdispatch.dylib                   0x0000000180b5214c _dispatch_lane_serial_drain$VARIANT$armv81
11  libdispatch.dylib                   0x0000000180b52c38 _dispatch_lane_invoke$VARIANT$armv81
12  libdispatch.dylib                   0x0000000180b53d84 _dispatch_workloop_invoke$VARIANT$armv81
13  libdispatch.dylib                   0x0000000180b5c5dc _dispatch_workloop_worker_thread
14  libsystem_pthread.dylib             0x00000001db3b6e84 _pthread_wqthread
Thread 23:
0   libsystem_kernel.dylib              0x00000001baf250cc __workq_kernreturn
1   libsystem_pthread.dylib             0x00000001db3b6ed0 _pthread_wqthread
Thread 24:
0   libsystem_kernel.dylib              0x00000001baf24b64 semaphore_timedwait_trap
1   libdispatch.dylib                   0x0000000180b4672c _dispatch_sema4_timedwait$VARIANT$armv81
2   libdispatch.dylib                   0x0000000180b46cbc _dispatch_semaphore_wait_slow
3   libdispatch.dylib                   0x0000000180b5b108 _dispatch_worker_thread
4   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 25:
0   libsystem_kernel.dylib              0x00000001baf24b64 semaphore_timedwait_trap
1   libdispatch.dylib                   0x0000000180b4672c _dispatch_sema4_timedwait$VARIANT$armv81
2   libdispatch.dylib                   0x0000000180b46cbc _dispatch_semaphore_wait_slow
3   libdispatch.dylib                   0x0000000180b5b108 _dispatch_worker_thread
4   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 26:
0   libsystem_kernel.dylib              0x00000001baf24b64 semaphore_timedwait_trap
1   libdispatch.dylib                   0x0000000180b4672c _dispatch_sema4_timedwait$VARIANT$armv81
2   libdispatch.dylib                   0x0000000180b46cbc _dispatch_semaphore_wait_slow
3   libdispatch.dylib                   0x0000000180b5b108 _dispatch_worker_thread
4   libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 27 Crashed:
0   libobjc.A.dylib                     0x00000001981fd470 objc_release
1   Foundation                          0x000000018259b528 -[_NSThreadPerformInfo dealloc]
2   Foundation                          0x0000000182593874 __NSThreadPerformPerform
3   CoreFoundation                      0x0000000180ecb2b0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
4   CoreFoundation                      0x0000000180edb2d8 __CFRunLoopDoSource0
5   CoreFoundation                      0x0000000180e1e6dc __CFRunLoopDoSources0
6   CoreFoundation                      0x0000000180e23aa8 __CFRunLoopRun
7   CoreFoundation                      0x0000000180e36e1c CFRunLoopRunSpecific
8   Foundation                          0x00000001825703cc -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
9   mama                                0x0000000106762280 +[LEBAsyncSocket cfstreamThread]
10  Foundation                          0x00000001825bc8ac __NSThread__start__
11  libsystem_pthread.dylib             0x00000001db3b83a4 _pthread_start
Thread 27 crashed with ARM-64 Thread State:
  cpsr: 0x0000000020000000     fp: 0x000000016bf51d70     lr: 0x000000018259b528     pc: 0x00000001981fd470 
    sp: 0x000000016bf51d40     x0: 0x0000000133a36460     x1: 0x000000019bdd65d7    x10: 0x0000000000000084 
   x11: 0x006800019f164ab1    x12: 0x0000000000d00e00    x13: 0x000001a1f2f625d9    x14: 0x0000000000000001 
   x15: 0x00000001f2f625d8    x16: 0x00000001981fd460    x17: 0x000000018259b4f4    x18: 0x0000000000000000 
   x19: 0x00000002816dd480     x2: 0x0000000000000100    x20: 0x0000000280f8a390    x21: 0x000000019b1165bb 
   x22: 0x000000019b0d9b4e    x23: 0x0000000000000000    x24: 0x00000002816dd480    x25: 0x0000000132b7f058 
   x26: 0x0000000000000000    x27: 0x00000001f2f5d000    x28: 0x00000001f2f5d000    x29: 0x000000016bf51d70 
    x3: 0x0000000000000000     x4: 0x00000000000030a0     x5: 0x0000000000000101     x6: 0x0000000000000000 
    x7: 0x0000000000000000     x8: 0xf000000000000000     x9: 0x0000000000000000 
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by lebosdk** [comment]
根据开发人员分析，目前更新的版本已经解决您报的问题，请用新版本尝试看看

**Comment by peter-Kings** [comment]
你的邮件已收到，我会尽快处理并给予回复！！！

**Comment by peter-Kings** [comment]
> 根据开发人员分析，目前更新的版本已经解决您报的问题，请用新版本尝试看看

你好，我的LBLelinkKit库版本已经是30706，是最新的了。。。。。

**Comment by lebosdk** [comment]
我们的版本在github上和cocoapods已经更新到31306了，昨天（2022-3-9）上午发布成功的，我们的开发人员pod是可以正常更新到这个版本的，您再试试看

**Comment by peter-Kings** [comment]
> 
搜到了，已经更新了，谢谢
