### ISSUE TITLE
电视机正在播放上一次投屏，第二次投屏并没有生效

### ISSUE THREAD

**Issue by hegelsu** [lebosdk/LBLelinkKit#2]
电视机正在播放上一次投屏，第二次投屏并没有生效，而且导致第一次投屏播放退出了，要重新投一次才有效，感觉是如果当前正在播放投屏内容，那么你再投屏就会使当前正在播放的退出，只有当前没有播放投屏内容时，投屏结果才有效，这个如何处理？

**Comment by lebosdk** [comment]
这跟接收端有关系，你可以尝试安装我们的最新TV接收端apk试试
