### ISSUE TITLE
sdk crash

### ISSUE THREAD

**Issue by wayneYo** [lebosdk/LBLelinkKit#6]
_tlv_box_putobject + 88
 _tlv_box_parse + 140
+[LBShakeHandsTool shakeHandsEcdhM1Server:dataVerify:] + 124
 -[LBLelinkBaseSocket responseLelinkSetupSingleData:] + 276
 -[LBLelinkBaseSocket parseSingleData:] + 688
 -[LBLelinkPositiveSocket parseSingleData:] + 64
 -[LBLelinkBaseSocket takeApartForPacketFromData:] + 844
 -[LBLelinkBaseSocket socket:didReadData:withTag:] + 156
___37-[LEBAsyncSocket completeCurrentRead]_block_invoke + 56

**Comment by lebosdk** [comment]
已经更新了版本，目前到31306了，请用新版本试试看

**Comment by lebosdk** [comment]
与其它库冲突，请采用本地集成方式可解决
