### ISSUE TITLE
iOS14 权限

### ISSUE THREAD

**Issue by Lius1104** [lebosdk/LBLelinkKit#7]
[ERROR] --{ error:Error Domain=LBLelinkBrowserErrorDomain Code=-1500 "(null)" UserInfo={errorInfo=Missing required configuration for local network access.NSBonjourServices and NSLocalNetworkUsageDescription are required in Info.plist!} }-- -[LBLelinkBrowser searchForLelinkServiceOfType:]:446:<NSThread: 0x280ec4300>{number = 1, name = main}:LBLelinkBrowser.m

NSBonjourServices 怎么配置

**Comment by rnkyr** [comment]
@Lius1104, have you resolved the issue? I'm currently facing it and have no clue what's going on

**Comment by lebosdk** [comment]
Info.plist中需要配置NSBonjourServices(_leboremote._tcp)和NSLocalNetworkUsageDescription，兼容iOS14

**Comment by lebosdk** [comment]
详情参考：https://doc.hpplay.com.cn/web/#/1/55
